import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

import '../../shared/themes/app_theme.dart';

class ThemeService extends GetxService {
  int _currentIndex = 0;

  int get currentIndex => _currentIndex;
  String get currentName => _presets[_currentIndex].name;
  List<String> get presetNames => _presets.map((p) => p.name).toList();
  int get presetCount => _presets.length;

  void apply(int index) {
    if (index < 0 || index >= _presets.length) return;
    _currentIndex = index;
    AppTheme.current = _presets[index];
  }

  static final List<ThemePreset> _presets = [
    const ThemePreset(
      name: '深空靛蓝',
      background: Color(0xFF0F0F1A),
      surface: Color(0xFF1A1A2E),
      surfaceLight: Color(0xFF252542),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFF4F46E5),
      accentLight: Color(0xFF6366F1),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFCBD5E1),
      textMuted: Color(0xFF9CA3AF),
      chatBubbleMe: Color(0xFF4F46E5),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '极光绿',
      background: Color(0xFF0A1A0F),
      surface: Color(0xFF142E1A),
      surfaceLight: Color(0xFF1E4228),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFF059669),
      accentLight: Color(0xFF10B981),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFD1FAE5),
      textMuted: Color(0xFF9CA3AF),
      chatBubbleMe: Color(0xFF059669),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '暗夜紫',
      background: Color(0xFF0F0A1A),
      surface: Color(0xFF1A142E),
      surfaceLight: Color(0xFF282042),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFF7C3AED),
      accentLight: Color(0xFF8B5CF6),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFE9D5FF),
      textMuted: Color(0xFF9CA3AF),
      chatBubbleMe: Color(0xFF7C3AED),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '海洋蓝',
      background: Color(0xFF0A0F1A),
      surface: Color(0xFF14202E),
      surfaceLight: Color(0xFF1E3042),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFF2563EB),
      accentLight: Color(0xFF3B82F6),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFDBEAFE),
      textMuted: Color(0xFF9CA3AF),
      chatBubbleMe: Color(0xFF2563EB),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '落日橙',
      background: Color(0xFF1A0F0A),
      surface: Color(0xFF2E1A14),
      surfaceLight: Color(0xFF42281E),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFFD97706),
      accentLight: Color(0xFFF59E0B),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF97316),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFFEF3C7),
      textMuted: Color(0xFFD4A574),
      chatBubbleMe: Color(0xFFD97706),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '樱花粉',
      background: Color(0xFF1A0F14),
      surface: Color(0xFF2E1A24),
      surfaceLight: Color(0xFF422838),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFFDB2777),
      accentLight: Color(0xFFF472B6),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFFCE7F3),
      textMuted: Color(0xFFD495B8),
      chatBubbleMe: Color(0xFFDB2777),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '石墨灰',
      background: Color(0xFF0F0F11),
      surface: Color(0xFF1C1C1F),
      surfaceLight: Color(0xFF2C2C30),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFF6366F1),
      accentLight: Color(0xFF818CF8),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFD4D4D8),
      textMuted: Color(0xFFA1A1AA),
      chatBubbleMe: Color(0xFF6366F1),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '翡翠绿',
      background: Color(0xFF0A1412),
      surface: Color(0xFF0F1F1A),
      surfaceLight: Color(0xFF1A2E26),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFF0D9488),
      accentLight: Color(0xFF14B8A6),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF59E0B),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFCCFBF1),
      textMuted: Color(0xFF94A3B8),
      chatBubbleMe: Color(0xFF0D9488),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
    const ThemePreset(
      name: '赛博黄',
      background: Color(0xFF0A0A0A),
      surface: Color(0xFF1A1A1A),
      surfaceLight: Color(0xFF2A2A2A),
      glassBg: Color(0x0DFFFFFF),
      glassBorder: Color(0x1AFFFFFF),
      divider: Color(0x33FFFFFF),
      accent: Color(0xFFEAB308),
      accentLight: Color(0xFF84CC16),
      success: Color(0xFF22C55E),
      warning: Color(0xFFF97316),
      danger: Color(0xFFEF4444),
      textPrimary: Color(0xFFFFFFFF),
      textSecondary: Color(0xFFFEF9C3),
      textMuted: Color(0xFFA3A3A3),
      chatBubbleMe: Color(0xFFEAB308),
      chatBubbleOther: Color(0x1AFFFFFF),
    ),
  ];
}
